            - name: data-factory-validate
  uses: Azure/data-factory-validate-action@v1.1.5
  with:
    # Directory that contains all Data Factory resources
    path: # optional, default is ./
    # Data Factory resource ID
    id: # optional, default is /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resourceGroup/providers/Microsoft.DataFactory/factories/dataFactory
          
